### ISSUE TITLE
[Feature Request] port to Plasma 6 and QT 6

### ISSUE THREAD

**Issue by OzzyHelix** [rkstrdee/Jade#1]
KDE Plasma has updated to Plasma 6 and uses QT 6 would you be willing to make a port to QT 6 and Plasma 6 so people can still use this theme.
Sincerely Ozzy

**Comment by ddh4r4m** [comment]
Lemme see Ozzy, haven't gone through what updated. Will check and try to make the port.

**Comment by ddh4r4m** [comment]
This is done, You can download it from the store https://store.kde.org/p/2136809

**Comment by OzzyHelix** [comment]
![image](https://github.com/ddh4r4m/Jade/assets/29835364/06b1bcbf-0125-4633-9b3d-1dae84f45b2a)

**Comment by ddh4r4m** [comment]
Try again, Just downloaded, it worked fine for me

**Comment by OzzyHelix** [comment]
ok the problem was having the theme from KDE 5 installed

**Comment by OzzyHelix** [comment]
the old files were conflicting

**Comment by ddh4r4m** [comment]
Awesome.

**Comment by OzzyHelix** [comment]
I noticed that setting a different icon set overrides the system tray icons so it doesn't stay with the ones from the theme that is weird
![image](https://github.com/ddh4r4m/Jade/assets/29835364/b210acbb-ebb6-42fe-8152-d756df60f399)
